#!/usr/bin/env python3
"""tools/filespics.py: write assets/js/files-pics-data.js from the repo.

/files/ shows every picture under assets/img/archive/ in one grid. The text
beside each one is NOT written here: every picture already has a title, a line
under it and alt text where it is shown on its own page, either in a fan-*.js
data file or in a flyer caption in the page markup. This script harvests those
and re-shapes them, so the index can never describe a picture differently from
the page it lives on.

That is the whole rule: assets/img/archive/ is the list, and the pages are the
captions. Adding a picture to a page and re-running this adds it here too.

    python3 tools/filespics.py          rewrite the data file
    python3 tools/filespics.py --check  exit 1 if it is out of date
"""

import glob
import html
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARCHIVE = os.path.join(ROOT, 'assets', 'img', 'archive')
OUT = os.path.join(ROOT, 'assets', 'js', 'files-pics-data.js')
EXT = ('.jpg', '.jpeg', '.png', '.webp')

# assets/img/archive/ folders that are NOT my own files and so do not belong
# on /files/. msu-mtc is the MSU and MTC material: flyers, decks and event
# photographs made for those organizations, which never came out of my iCloud
# Drive. They are shown on /msu-mtc/ and that is the only place they belong.
SKIP = {'msu-mtc'}

# group key -> (heading, the line under it, the page that shows them)
GROUPS = [
    ('star-wars', 'Star Wars',           'the anniversaries and the servers',    '/worlds/star-wars/'),
    ('home',      'The certificates',    'awards, records and screenshots',      '/high-school/'),
    ('minshawi',  'Al-Minsh\u0101w\u012b', 'three portraits and the server',     '/worlds/minshawi/'),
    ('arab',      'Arabic calligraphy',  'my name, written four ways',           '/worlds/arab/'),
    ('misc',      'The single pictures', 'one each, from three worlds',          '/worlds/egypt/'),
]
NAMED = {g[0] for g in GROUPS if g[0] != 'misc'}


def unesc(s):
    s = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), s)
    return html.unescape(s.replace("\\'", "'"))


def harvest():
    """src -> {title, desc, alt}, from the JS data files and the page markup."""
    rec = {}
    for f in glob.glob(os.path.join(ROOT, 'assets', 'js', '*.js')):
        if os.path.basename(f) == 'files-pics-data.js':
            continue                      # never read our own output
        s = open(f, encoding='utf-8', errors='ignore').read()
        for m in re.finditer(r"\{[^{}]*?src:\s*'([^']*archive/[^']*)'[^{}]*?\}", s, re.S):
            blk, src = m.group(0), m.group(1)
            d = rec.setdefault(src, {})
            for key in ('title', 'desc', 'alt'):
                hit = re.search(r"%s:\s*'((?:[^'\\]|\\.)*)'" % key, blk)
                if hit:
                    d.setdefault(key, unesc(hit.group(1)))

    pages = glob.glob(os.path.join(ROOT, 'src', '*.html')) + [os.path.join(ROOT, 'index.html')]
    for f in pages:
        s = open(f, encoding='utf-8', errors='ignore').read()
        # a flyer: the link, its <img alt>, then <b>title</b><i>line</i>
        for m in re.finditer(r'href="([^"]*archive/[^"]*)"[^>]*>\s*<img[^>]*alt="([^"]*)"'
                             r'[^>]*/?>\s*<span class="flyer-cap"><b>(.*?)</b><i>(.*?)</i>', s, re.S):
            d = rec.setdefault(m.group(1), {})
            d.setdefault('alt', html.unescape(m.group(2)))
            d.setdefault('title', html.unescape(re.sub('<[^>]+>', '', m.group(3))))
            d.setdefault('desc', html.unescape(re.sub('<[^>]+>', '', m.group(4))))
        for m in re.finditer(r'<img[^>]*src="([^"]*archive/[^"]*)"[^>]*alt="([^"]*)"', s):
            rec.setdefault(m.group(1), {}).setdefault('alt', html.unescape(m.group(2)))
    return rec


def pictures():
    out = subprocess.run(['find', ARCHIVE, '-type', 'f'],
                         capture_output=True, text=True).stdout.split('\n')
    rel = sorted('/' + os.path.relpath(p, ROOT) for p in out
                 if p.strip() and p.lower().endswith(EXT))
    return [p for p in rel
            if p.split('/assets/img/archive/')[1].split('/')[0] not in SKIP]


def group_of(p):
    key = p.split('/assets/img/archive/')[1].split('/')[0]
    return key if key in NAMED else 'misc'


def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


def render(rec, imgs):
    L = ["/* files-pics-data.js: every picture in assets/img/archive/, for /files/.",
         "",
         "   GENERATED by tools/filespics.py. Do not edit by hand: the title, the line",
         "   under it and the alt text are the ones already written where each picture",
         "   is shown (the fan-*.js data files and the flyer captions in the pages), so",
         "   this file is a second copy of them and nothing here is new prose.",
         "",
         "   Re-run the script after adding or removing anything under that folder;",
         "   tools/check.py fails if the two drift apart. */",
         "window.FILESPICS = ["]
    for key, label, note, href in GROUPS:
        mem = [p for p in imgs if group_of(p) == key]
        if not mem:
            continue
        L.append("  { id: '%s', label: '%s', note: '%s', href: '%s', items: ["
                 % (key, esc(label), esc(note), href))
        for p in mem:
            r = rec.get(p, {})
            L.append("    { src: '%s', title: '%s'," % (p, esc(r.get('title', ''))))
            if r.get('desc'):
                L.append("      desc: '%s'," % esc(r['desc']))
            L.append("      alt: '%s' }," % esc(r.get('alt', '')))
        L.append("  ] },")
    L.append("];")
    return '\n'.join(L) + '\n'


def main():
    rec, imgs = harvest(), pictures()
    if not imgs:
        sys.exit('filespics.py: no pictures found under assets/img/archive/')
    missing = [p for p in imgs if not rec.get(p, {}).get('title')]
    text = render(rec, imgs)

    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            sys.exit('assets/js/files-pics-data.js is out of date: run python3 tools/filespics.py')
        print('files-pics-data.js up to date (%d pictures)' % len(imgs))
        return

    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s: %d pictures' % (os.path.relpath(OUT, ROOT), len(imgs)))
    if missing:
        print('  %d with no title where they are shown:' % len(missing))
        for m in missing[:10]:
            print('   ', m)


if __name__ == '__main__':
    main()
