#!/usr/bin/env python3
"""Write the content hashes the cache busting runs on.

  _data/versions.yml        every CSS and JS file      (read by _includes/v.html)
  _data/photo_versions.yml  every gallery photograph   (read by sw.js only)

_includes/v.html appends ?v=<hash> to stylesheet and script URLs so a changed
file is a new URL and an unchanged one keeps its cached copy. It used to use
the file's modified time, but GitHub Pages builds from a fresh checkout where
every file's mtime is the checkout time, so every deploy changed every URL
and made every visitor re-download all of it. A hash of the content only
changes when the content does, on any machine.

The photographs get the same treatment for a different reader. Pages ask for
them by their plain path, but the service worker stores each one under
path?v=<hash>, so a photograph replaced under the same filename is a new
cache entry: the background fill fetches it and the old copy is pruned. Without
this the fill saw "already have it" and kept the stale one for good. Hashing
half a gigabyte on every commit would be slow, so a file's hash is remembered
against its size and mtime in .jekyll-cache/ and only re-read when those move.

Runs from the pre-commit hook in tools/hooks (installed by ./run) and from
./run itself, so both files are always current. Safe to run by hand.
"""
import hashlib, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, '_data')
CACHE = os.path.join(ROOT, '.jekyll-cache', 'stamp-photos.json')   # gitignored
PHOTO_DIRS = ('assets/img/years', 'assets/img/years-large')

def sha(full):
    with open(full, 'rb') as fh:
        return hashlib.sha1(fh.read()).hexdigest()[:10]

def walk(subs, exts):
    for sub in subs:
        for dirpath, _, files in os.walk(os.path.join(ROOT, sub)):
            for name in files:
                if name.startswith('.') or (exts and not name.endswith(exts)):
                    continue
                full = os.path.join(dirpath, name)
                yield '/' + os.path.relpath(full, ROOT).replace(os.sep, '/'), full

def write(path, header, entries):
    body = '# Generated by tools/stamp.py: %s. Do not edit.\n' % header
    body += ''.join('"%s": "%s"\n' % (p, d) for p, d in sorted(entries))
    old = open(path).read() if os.path.exists(path) else None
    if body == old:
        return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(body)
    return 1

def code():
    return [(rel, sha(full)) for rel, full in walk(('assets/css', 'assets/js'), ('.css', '.js'))]

def photos():
    try:
        with open(CACHE) as fh:
            known = json.load(fh)
    except (OSError, ValueError):
        known = {}
    fresh, entries = {}, []
    for rel, full in walk(PHOTO_DIRS, ()):
        st = os.stat(full)
        stamp = [st.st_size, int(st.st_mtime)]
        hit = known.get(rel)
        digest = hit[2] if hit and hit[:2] == stamp else sha(full)
        fresh[rel] = stamp + [digest]
        entries.append((rel, digest))
    if fresh != known:
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        with open(CACHE, 'w') as fh:
            json.dump(fresh, fh)
    return entries

def main():
    changed  = write(os.path.join(DATA, 'versions.yml'),
                     'content hashes used by _includes/v.html', code())
    changed += write(os.path.join(DATA, 'photo_versions.yml'),
                     'content hashes of the gallery photographs, used by sw.js', photos())
    return changed

if __name__ == '__main__':
    changed = main()
    if '--quiet' not in sys.argv:
        n = lambda f: sum(1 for _ in open(os.path.join(DATA, f))) - 1
        print('versions.yml %s (%d files), photo_versions.yml (%d photographs)'
              % ('updated' if changed else 'unchanged', n('versions.yml'), n('photo_versions.yml')))
