#!/usr/bin/env python3
"""Write _data/versions.yml: a short content hash for every CSS and JS file.

_includes/v.html appends ?v=<hash> to stylesheet and script URLs so a changed
file is a new URL and an unchanged one keeps its cached copy. It used to use
the file's modified time, but GitHub Pages builds from a fresh checkout where
every file's mtime is the checkout time, so every deploy changed every URL
and made every visitor re-download all of it. A hash of the content only
changes when the content does, on any machine.

Runs from the pre-commit hook in tools/hooks (installed by ./run) and from
./run itself, so the file is always current. Safe to run by hand.
"""
import hashlib, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, '_data', 'versions.yml')

def main():
    entries = []
    for sub in ('assets/css', 'assets/js'):
        for dirpath, _, files in os.walk(os.path.join(ROOT, sub)):
            for name in files:
                if not name.endswith(('.css', '.js')):
                    continue
                full = os.path.join(dirpath, name)
                with open(full, 'rb') as fh:
                    digest = hashlib.sha1(fh.read()).hexdigest()[:10]
                rel = '/' + os.path.relpath(full, ROOT).replace(os.sep, '/')
                entries.append((rel, digest))
    entries.sort()
    body = '# Generated by tools/stamp.py: content hashes used by _includes/v.html. Do not edit.\n'
    body += ''.join('"%s": "%s"\n' % (p, d) for p, d in entries)
    old = open(OUT).read() if os.path.exists(OUT) else None
    if body != old:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, 'w') as fh:
            fh.write(body)
        return 1
    return 0

if __name__ == '__main__':
    changed = main()
    if '--quiet' not in sys.argv:
        print('versions.yml %s (%d files)' % ('updated' if changed else 'unchanged', sum(1 for _ in open(OUT)) - 1))
