#!/usr/bin/env node
/* tools/themes.js: writes assets/js/music-themes.js, the "Themes" section at
   the foot of /music/: the main theme of every world on the site.

       node tools/themes.js

   NOTHING IS COPIED BY HAND. Every track already lives once, on its own worlds
   page (a `themes` / `music` / `score` section in that page's fan-*.js, with a
   YouTube id that was checked when it was added). This reads those data files
   the way the page does, takes ONE track per world, and writes the result out
   as a generated file, the same way tools/photos.py writes years-data.js. Change
   a track on its worlds page and run this again; never edit the output.

   WHICH TRACK. The first track of the world's own music list, unless MAIN
   below names the one that is actually the main theme: a list often opens with
   a deep cut or a newer series and puts the famous theme further down. A world
   with no music on its page (Islam, the Qurʾān, Egypt, Knott's, Roblox and so
   on) is simply not in the list. */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'assets', 'js', 'music-themes.js');

/* page -> a pattern for the track title that is the world's main theme */
const MAIN = {
  '/worlds/star-wars/': /^Main Title/i,
  '/worlds/avengers/': /^The Avengers/i,
  '/worlds/game-of-thrones/': /^Main Title/i,
  '/worlds/minecraft/': /^Sweden$/i,
  '/worlds/pirates/': /^He'?s a Pirate/i,
  '/worlds/lord-of-the-rings/': /^Concerning Hobbits/i,
  '/worlds/pixar/': /^You'?ve Got a Friend in Me/i,
  '/worlds/spongebob/': /SquarePants/i,
  '/worlds/christopher-nolan/': /^Time$/i,
  '/worlds/justice-league/': /^Justice League/i,
  '/worlds/ninjago/': /Weekend Whip/i,
  '/worlds/how-to-train-your-dragon/': /^Test Drive/i,
};

const MUSIC_ID = /(^|-)(themes?|music|score|soundtrack)($|-)/i;
const MUSIC_TITLE = /\b(themes?|music|score|soundtrack)\b/i;
const YT = /(?:youtube\.com\/watch\?(?:.*&)?v=|youtu\.be\/)([A-Za-z0-9_-]{6,})/;
/* sections a page borrows from ANOTHER world (Avengers shows Spider-Man's
   music, the Justice League shows Batman's): never the page's own theme */
const BORROWED = /^(spider-music|batman-music|unofficial-songs|reels-songs|songs)$/;

const ytOf = (it) => {
  const hrefs = [it.href].concat((it.links || []).map((l) => l.href));
  for (const h of hrefs) { const m = YT.exec(String(h || '')); if (m) return m[1]; }
  return '';
};

const out = [];
for (const file of fs.readdirSync(path.join(ROOT, 'src')).sort()) {
  if (!/^fan-.*\.html$/.test(file)) continue;
  const html = fs.readFileSync(path.join(ROOT, 'src', file), 'utf8');
  if (/^published:\s*false/m.test(html)) continue;
  const page = (html.match(/^permalink:\s*(\S+)/m) || [])[1];
  const name = ((html.match(/^title:\s*"([^"]+)"/m) || [])[1] || '').split(' · ')[0]
    .replace(/&#183;.*$/, '').replace(/&#8217;/g, '’').trim();
  const tag = (html.match(/data-fan="([^"]+)"/) || [])[1];
  const scripts = [...html.matchAll(/f='\/assets\/js\/([^']+\.js)'/g)].map((m) => m[1])
    .filter((s) => /^(fan-|lego-games|batman-music|spider-man-music)/.test(s)
      && !/^(fan-shots|fan-been|fan-engine)/.test(s) && !/-ui\.js$/.test(s));

  global.window = {};
  global.document = { getElementById: () => null, querySelector: () => null,
    querySelectorAll: () => [], body: { getAttribute: () => tag } };
  for (const s of scripts) {
    try { eval(fs.readFileSync(path.join(ROOT, 'assets', 'js', s), 'utf8')); } catch (e) { /* a UI file */ }
  }
  const P = global.window.FAN_PAGE;
  if (!P) continue;

  const tracks = [];
  for (const s of (P.sections || []).filter(Boolean)) {
    if (BORROWED.test(s.id || '')) continue;
    if (!MUSIC_ID.test(s.id || '') && !MUSIC_TITLE.test(s.title || '')) continue;
    for (const it of s.items || []) { const v = ytOf(it); if (v) tracks.push({ it, v }); }
  }
  if (!tracks.length) continue;
  const want = MAIN[page];
  const pick = (want && tracks.find((x) => want.test(x.it.title))) || tracks[0];
  if (want && !want.test(pick.it.title)) console.warn('! %s: no track matches %s, took %s', page, want, pick.it.title);
  out.push({ w: name, href: page, t: pick.it.title, a: pick.it.sub || '', v: pick.v });
}

out.sort((a, b) => a.w.localeCompare(b.w));
const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const lines = out.map((x) => '  { w: ' + q(x.w) + ', href: ' + q(x.href) + ', t: ' + q(x.t)
  + ', a: ' + q(x.a) + ', v: ' + q(x.v) + ' },');
fs.writeFileSync(OUT, `/* music-themes.js: the main theme of every world, for the Themes section at
   the foot of /music/. GENERATED by \`node tools/themes.js\` from the worlds
   pages' own data files; edit a track there and run it again, never here.

     w     the world, as its page is titled
     href  its page
     t     the track, a its line (composer, film, year), v its YouTube id */
window.MUSIC_THEMES = [
${lines.join('\n')}
];
`);
console.log('wrote %s: %d worlds', path.relative(ROOT, OUT), out.length);
