#!/usr/bin/env python3
"""tools/worlds.py: write _data/worlds.yml from assets/js/fandom-data.js.

WHY THIS EXISTS. Every world page ends with the other worlds in its own
section: inside the Core Three you get the other two, inside Primary you get
all of Primary. That needs each page to know its group and its group's other
members, and there were three ways to do it:

  1. hand-write the list into all 72 pages. Seventy-two copies of something
     fandom-data.js already states, wrong the first time a tile moves rank.
  2. load fandom-data.js on every world page and group it in the browser.
     27 KB and a render pass on all 72 pages, to print a dozen names.
  3. derive it once, at author time, into the _data file Jekyll already
     reads, and let Liquid print it server-side. No new JS, no new payload.

This is (3), and the rule that keeps it honest is that fandom-data.js stays
the single source of truth: this script never invents anything, it only
re-shapes what is already there. Run it after adding, renaming, re-ranking
or re-linking a tile; tools/check.py fails if the two drift apart.

    python3 tools/worlds.py          rewrite _data/worlds.yml
    python3 tools/worlds.py --check  exit 1 if it is out of date (CI/check.py)
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'js', 'fandom-data.js')
OUT = os.path.join(ROOT, '_data', 'worlds.yml')

# { id: 'core', label: 'The Core Three', note: '...', items: [
GROUP = re.compile(
    r"\{\s*id:\s*'([a-z0-9-]+)',\s*label:\s*'((?:[^'\\]|\\.)*)',"
    r"\s*note:\s*'((?:[^'\\]|\\.)*)',\s*items:\s*\[", re.S)

# a tile's name, and its href if it has one. Both are single-quoted in the
# source and may carry \u escapes and \' for an apostrophe.
NAME = re.compile(r"\{\s*name:\s*'((?:[^'\\]|\\.)*)'", re.S)
HREF = re.compile(r"href:\s*'(/[^']*)'")


def unescape(s):
    """The source is JS single-quoted: \\u2019 and \\' both appear."""
    return re.sub(r'\\u([0-9a-fA-F]{4})',
                  lambda m: chr(int(m.group(1), 16)),
                  s.replace("\\'", "'"))


def tiles_of(block):
    """Every tile in one group's items: [ ... ] block, in source order."""
    out = []
    # split on the start of each tile object, keeping each tile's own text
    starts = [m.start() for m in NAME.finditer(block)]
    for i, a in enumerate(starts):
        b = starts[i + 1] if i + 1 < len(starts) else len(block)
        chunk = block[a:b]
        name = unescape(NAME.search(chunk).group(1))
        href = HREF.search(chunk)
        out.append({'name': name, 'href': href.group(1) if href else None})
    return out


def parse():
    js = open(SRC, encoding='utf-8').read()
    groups = []
    marks = list(GROUP.finditer(js))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(js)
        groups.append({
            'id': m.group(1),
            'label': unescape(m.group(2)),
            'note': unescape(m.group(3)),
            'items': tiles_of(js[m.end():end]),
        })
    return groups


def yaml_str(s):
    """Quote for YAML: these carry apostrophes and non-ASCII, never newlines."""
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def render(groups):
    L = ["# GENERATED by tools/worlds.py from assets/js/fandom-data.js.",
         "# Do not edit by hand: edit fandom-data.js and re-run the script.",
         "#",
         "# Each world page prints the other worlds in its own section from",
         "# this file (_includes/world-siblings.html), so a page knows its",
         "# neighbors without loading the whole 27 KB tile catalog.",
         ""]
    for g in groups:
        L.append('- id: %s' % g['id'])
        L.append('  label: %s' % yaml_str(g['label']))
        L.append('  note: %s' % yaml_str(g['note']))
        L.append('  items:')
        for t in g['items']:
            L.append('    - name: %s' % yaml_str(t['name']))
            if t['href']:
                L.append('      href: %s' % yaml_str(t['href']))
        L.append('')
    return '\n'.join(L).rstrip() + '\n'


def main():
    groups = parse()
    if not groups:
        sys.exit('worlds.py: parsed no groups from fandom-data.js')
    text = render(groups)
    n = sum(len(g['items']) for g in groups)

    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            sys.exit('_data/worlds.yml is out of date: run python3 tools/worlds.py')
        print('worlds.yml up to date (%d groups, %d worlds)' % (len(groups), n))
        return

    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s: %d groups, %d worlds' % (
        os.path.relpath(OUT, ROOT), len(groups), n))
    for g in groups:
        linked = sum(1 for t in g['items'] if t['href'])
        print('  %-10s %-22s %2d worlds, %2d linked' % (
            g['id'], g['label'], len(g['items']), linked))


if __name__ == '__main__':
    main()
